WEBHOOK_URL = "https://connect.pabbly.com/workflow/sendwebhookdata/IjU3NjUwNTY0MDYzZTA0M2M1MjY5NTUzNTUxMzEi_pc"
Work_url = "https://lottie.host/3633395b-e286-47ad-8a79-37b8e90f6d3e/31VLSdgr8N.json"
Skill_url = "https://lottie.host/00b5425f-2281-4c6c-a4c3-6de4cdddf4dd/YbsUNneZDg.json"
Comedy = "https://lottie.host/e8579c96-af6e-4ffe-b5a0-6c52bb7ab2e5/icmNgKQAk3.json"
prediction = "https://lottie.host/7d262c16-f4d3-4489-b5f5-fbff35cb74f5/YmxSNVMQcl.json"